"""empty message

Revision ID: 36eacc481a8b
Revises: c1b455ed0562
Create Date: 2021-09-16 08:23:56.022662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36eacc481a8b'
down_revision = '73f71698c503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'template', 'template_content', ['current_content'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'current_content')
    # ### end Alembic commands ###
