"""empty message

Revision ID: c1b455ed0562
Revises: 
Create Date: 2021-09-16 08:23:19.240983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1b455ed0562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_content', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_created_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_modified_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_deleted_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('template_content',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_created_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('jinja2', name='templatetype'), nullable=False),
    sa.Column('input_data_json_schema', sa.JSON(), nullable=False),
    sa.Column('default_data', sa.JSON(), nullable=False),
    sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_message_log',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_created', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('result_content', sa.Text(), nullable=False),
    sa.Column('email_to', sa.String(length=1000), nullable=False),
    sa.Column('template_content_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['template_content_id'], ['template_content.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_message_log')
    op.drop_table('template_content')
    op.drop_table('template')
    op.execute('DROP TYPE templatetype;')
    # ### end Alembic commands ###
